## Feature Transformation
Missing Values Imputation , Handling categorical values , Outlier detection , Feature Scaling 

Feature Transform - Encoding 
1. Label Encoder is specifically used for target variables which is categorical .for example spam classifier target variable(y) - yes/no
2. Ordinal encoder is used for input variables (x) where x variable is ordinal categorical data .Ordinal means order .such as reviews Good ,better , worst . we can see order that is good > better > worst
3. One Hot encoder  is used where input categorical variable is nominal that is not ordered.such as states , engineering branches we can't say that state is better than this state 

### Ordinal Encoding

In [1]:
import pandas as pd
import numpy as np

In [13]:
df = pd.read_csv(r"C:\Users\karth\Downloads\customer.csv")

In [14]:
df.sample(5)

,age,gender,review,education,purchased
39,76,Male,Poor,PG,No
22,18,Female,Poor,PG,Yes
44,77,Female,Average,UG,No
41,23,Male,Good,PG,Yes
24,16,Female,Average,PG,Yes


#### Gender is nominal data there is no order just category male and female . 'Nominal Encoder'
#### Review ,education is a ordinal data 'Ordinal Encoder'
#### Purchased is our target variable 'Label Encoder'

In [15]:
# as of now we are ignoring gender n age 
df= df.iloc[:,2:]

In [16]:
df.head()

,review,education,purchased
0,Average,School,No
1,Poor,UG,No
2,Good,PG,No
3,Good,PG,No
4,Average,UG,No


In [17]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df.iloc[:,0:2],df.iloc[:,-1],test_size=0.2)

In [20]:
X_train

,review,education
46,Poor,PG
20,Average,School
6,Good,School
48,Good,UG
22,Poor,PG
26,Poor,PG
5,Average,School
38,Good,School
0,Average,School
2,Good,PG


In [22]:
from sklearn.preprocessing import OrdinalEncoder

In [23]:
## I am just giving categories in a order from low value to high value so good will get high value than poor and average
##  If i will not give categories randomly it will provide values 
oe = OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']])


In [24]:
oe.fit(X_train)


OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])

In [25]:
X_train = oe.transform(X_train)
X_test = oe.transform(X_test)

In [26]:
X_train

array([[0., 2.],
       [1., 0.],
       [2., 0.],
       [2., 1.],
       [0., 2.],
       [0., 2.],
       [1., 0.],
       [2., 0.],
       [1., 0.],
       [2., 2.],
       [0., 2.],
       [2., 0.],
       [1., 0.],
       [1., 1.],
       [2., 1.],
       [2., 0.],
       [0., 1.],
       [0., 0.],
       [2., 1.],
       [2., 2.],
       [1., 2.],
       [0., 0.],
       [2., 1.],
       [2., 2.],
       [2., 0.],
       [1., 1.],
       [1., 1.],
       [0., 2.],
       [0., 1.],
       [2., 2.],
       [1., 1.],
       [0., 2.],
       [0., 0.],
       [0., 0.],
       [1., 0.],
       [0., 0.],
       [2., 0.],
       [0., 2.],
       [1., 1.],
       [0., 1.]])

In [27]:
oe.categories_

[array(['Poor', 'Average', 'Good'], dtype=object),
 array(['School', 'UG', 'PG'], dtype=object)]

### Label Encoding

In [29]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
#No parameters in labelencoder class as it will randomly decide what target column will get value .purchase (yes/no) 

In [30]:
le.fit(y_train)

LabelEncoder()

In [31]:
le.classes_

array(['No', 'Yes'], dtype=object)

In [32]:
y_train = le.transform(y_train)
y_test = le.transform(y_test)

In [33]:
y_train

array([0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0,
       1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0])

## Nominal Categorical Data 

### One Hot encoding

In [68]:
import pandas as pd
import numpy as np

In [69]:
df = pd.read_csv(r"C:\Users\karth\Downloads\cars.csv")

In [36]:
df.head()

,brand,km_driven,fuel,owner,selling_price
0,Maruti,145500,Diesel,First Owner,450000
1,Skoda,120000,Diesel,Second Owner,370000
2,Honda,140000,Petrol,Third Owner,158000
3,Hyundai,127000,Diesel,First Owner,225000
4,Maruti,120000,Petrol,First Owner,130000


In [43]:
df.brand.value_counts()

Maruti           2448
Hyundai          1415
Mahindra          772
Tata              734
Toyota            488
Honda             467
Ford              397
Chevrolet         230
Renault           228
Volkswagen        186
BMW               120
Skoda             105
Nissan             81
Jaguar             71
Volvo              67
Datsun             65
Mercedes-Benz      54
Fiat               47
Audi               40
Lexus              34
Jeep               31
Mitsubishi         14
Force               6
Land                6
Isuzu               5
Kia                 4
Ambassador          4
Daewoo              3
MG                  3
Ashok               1
Opel                1
Peugeot             1
Name: brand, dtype: int64

OHE  using most frquent values . We can see maruti ,hyundai,mahindra ,tata is most frequent.Brand such as kia ,land ,MG,ashok.opel etc is very few so we create one diffrent column where we will merge these less frequecnt brand in one just to reduce the dimension of the data as ohe hot encoding will create dummy variable of each brand which is 32 columns

In [44]:
df.sample(10)

,brand,km_driven,fuel,owner,selling_price
2071,Mahindra,130000,Diesel,First Owner,550000
5791,Maruti,80000,Diesel,First Owner,245000
5205,Hyundai,120000,Diesel,Second Owner,880000
791,Maruti,51000,Petrol,First Owner,100000
4233,Volvo,2000,Diesel,First Owner,2475000
7856,Honda,6550,Petrol,First Owner,725000
5685,Maruti,65000,Diesel,First Owner,900000
6622,Maruti,60000,Petrol,Second Owner,229999
3902,Ford,54000,Diesel,First Owner,300000
6008,Hyundai,54043,Petrol,First Owner,374000


In [46]:
# Number of Unique values in each faeture
df.nunique()

brand             32
km_driven        921
fuel               4
owner              5
selling_price    677
dtype: int64

In [47]:
df.owner.value_counts()

First Owner             5289
Second Owner            2105
Third Owner              555
Fourth & Above Owner     174
Test Drive Car             5
Name: owner, dtype: int64

In [48]:
df.fuel.value_counts()

Diesel    4402
Petrol    3631
CNG         57
LPG         38
Name: fuel, dtype: int64

### One hot encoding using pandas 

In [49]:
pd.get_dummies(df,columns=['fuel','owner'])

,brand,km_driven,selling_price,fuel_CNG,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_First Owner,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,0,1,0,0,1,0,0,0,0
1,Skoda,120000,370000,0,1,0,0,0,0,1,0,0
2,Honda,140000,158000,0,0,0,1,0,0,0,0,1
3,Hyundai,127000,225000,0,1,0,0,1,0,0,0,0
4,Maruti,120000,130000,0,0,0,1,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,0,0,0,1,1,0,0,0,0
8124,Hyundai,119000,135000,0,1,0,0,0,1,0,0,0
8125,Maruti,120000,382000,0,1,0,0,1,0,0,0,0
8126,Tata,25000,290000,0,1,0,0,1,0,0,0,0


### K-1 OneHotEncoding :
#### We are basically removing one dummy varible to avoid multicollinearity

In [50]:
pd.get_dummies(df,columns=['fuel','owner'],drop_first=True)

,brand,km_driven,selling_price,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,1,0,0,0,0,0,0
1,Skoda,120000,370000,1,0,0,0,1,0,0
2,Honda,140000,158000,0,0,1,0,0,0,1
3,Hyundai,127000,225000,1,0,0,0,0,0,0
4,Maruti,120000,130000,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,0,0,1,0,0,0,0
8124,Hyundai,119000,135000,1,0,0,1,0,0,0
8125,Maruti,120000,382000,1,0,0,0,0,0,0
8126,Tata,25000,290000,1,0,0,0,0,0,0


#### We transformed to categories we got 12 features now to avoid mutlicollinearity we will drop one column from each transformed category ,after dropping category we will get 10 features
### In machine learning we dont use get_dummines as  it doesnt remember what coding it has given so every tiume you re-run it will give encoding differently which is not the case in sklearn 

## OneHotEncoding using Sklearn 

In [70]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df.iloc[:,0:4],df.iloc[:,-1],test_size=0.2,random_state=2)

In [71]:
X_train.head()

,brand,km_driven,fuel,owner
5571,Hyundai,35000,Diesel,First Owner
2038,Jeep,60000,Diesel,First Owner
2957,Hyundai,25000,Petrol,First Owner
7618,Mahindra,130000,Diesel,Second Owner
6684,Hyundai,155000,Diesel,First Owner


In [72]:
from sklearn.preprocessing import OneHotEncoder

In [73]:
# ohe = OneHotEncoder()  # we are not removing first coln of transformed category so we will get 
ohe = OneHotEncoder(drop='first',sparse=False,dtype=np.int32) 
#this will remove first coln of each transformed  
#if we dont use sparse = False then when we do fit_Tansform we get sparse row format and later we have to do additional step toarray()


In [74]:
ohe.fit_transform(X_train[['fuel','owner']])

c:\Users\karth\anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


array([[1, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 0, 0],
       ...,
       [0, 0, 1, ..., 0, 0, 0],
       [1, 0, 0, ..., 1, 0, 0],
       [1, 0, 0, ..., 0, 0, 0]])

In [75]:
# X_train_new=ohe.fit_transform(X_train[['fuel','owner']]).toarray()
X_train_new=ohe.fit_transform(X_train[['fuel','owner']]) #when we do "sparse = False"

c:\Users\karth\anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


In [76]:
X_train_new.shape

(6502, 7)

In [77]:
# X_test_new=ohe.fit_transform(X_test[['fuel','owner']]).toarray()
X_test_new=ohe.fit_transform(X_test[['fuel','owner']]) #"sparse = False "

c:\Users\karth\anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


In [78]:
## Now we need to append above two array to brand and km_driven so first we convert both into array and than stack them horizontally

np.hstack((X_train[['brand','km_driven']].values,X_train_new)).shape

(6502, 9)

## OneHotEncoding with Top Categories

In [82]:
counts = df['brand'].value_counts()

In [83]:
df['brand'].nunique()
threshold = 100

In [87]:
# we are just saying cars less than 100 in value counts storing its index (name of brand) in repl 
repl=counts[counts<=threshold].index

In [89]:
# Whereever there is repl we put into ucommon column 
pd.get_dummies(df['brand'].replace(repl,'uncommon')).sample(10)


,BMW,Chevrolet,Ford,Honda,Hyundai,Mahindra,Maruti,Renault,Skoda,Tata,Toyota,Volkswagen,uncommon
2313,0,0,0,0,0,0,1,0,0,0,0,0,0
1185,0,0,0,0,0,0,0,0,0,0,1,0,0
7040,0,0,0,0,0,0,1,0,0,0,0,0,0
1407,0,0,0,0,0,0,0,0,0,0,0,0,1
7754,0,0,0,0,0,0,1,0,0,0,0,0,0
56,0,0,0,0,0,0,0,0,0,0,1,0,0
2395,0,0,0,0,0,1,0,0,0,0,0,0,0
2061,0,0,0,0,1,0,0,0,0,0,0,0,0
4846,0,0,0,0,0,0,0,1,0,0,0,0,0
1419,0,0,0,0,1,0,0,0,0,0,0,0,0
